/**
 * Opaque Admin Routing Architecture
 * Obfuscates administrative paths to prevent predictable enumeration.
 * NOTE: True security is enforced via JWT / session authentication in backend middleware.
 */

export const ADMIN_BASE_PATH = "/x7k9";

export const ADMIN_SUBPATHS = {
  OVERVIEW: "overview",
  BOOKINGS: "r4m8",
  ENQUIRIES: "q2p6",
  FRAMES: "f9k3",
  GALLERY: "g7v1",
  PORTFOLIO: "p3w5",
  SERVICES: "s8d4",
  FILMS: "m6j2",
  BRANCHES: "b5n7",
  TESTIMONIALS: "t1x9",
  CONTENT: "c4y8",
  SETTINGS: "k2h6",
};

export const ADMIN_ROUTES = {
  BASE: ADMIN_BASE_PATH,
  LOGIN: `${ADMIN_BASE_PATH}/login`,
  DASHBOARD: `${ADMIN_BASE_PATH}/${ADMIN_SUBPATHS.OVERVIEW}`,
  BOOKINGS: `${ADMIN_BASE_PATH}/${ADMIN_SUBPATHS.BOOKINGS}`,
  ENQUIRIES: `${ADMIN_BASE_PATH}/${ADMIN_SUBPATHS.ENQUIRIES}`,
  FRAMES: `${ADMIN_BASE_PATH}/${ADMIN_SUBPATHS.FRAMES}`,
  GALLERY: `${ADMIN_BASE_PATH}/${ADMIN_SUBPATHS.GALLERY}`,
  PORTFOLIO: `${ADMIN_BASE_PATH}/${ADMIN_SUBPATHS.PORTFOLIO}`,
  SERVICES: `${ADMIN_BASE_PATH}/${ADMIN_SUBPATHS.SERVICES}`,
  FILMS: `${ADMIN_BASE_PATH}/${ADMIN_SUBPATHS.FILMS}`,
  BRANCHES: `${ADMIN_BASE_PATH}/${ADMIN_SUBPATHS.BRANCHES}`,
  TESTIMONIALS: `${ADMIN_BASE_PATH}/${ADMIN_SUBPATHS.TESTIMONIALS}`,
  CONTENT: `${ADMIN_BASE_PATH}/${ADMIN_SUBPATHS.CONTENT}`,
  SETTINGS: `${ADMIN_BASE_PATH}/${ADMIN_SUBPATHS.SETTINGS}`,
};

export default ADMIN_ROUTES;
